### ISSUE TITLE
Description of the Kafka & Hystrix Dashboard Kubernetes Application are not correct

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#5940] opened 2016-04-15 16:44 UTC
Description of the Kafka & Hystrix Dashboard Kubernetes Application refer to Sonatype

 ![screenshot 2016-04-15 18 42 46](https://cloud.githubusercontent.com/assets/463790/14568576/0b690eb2-033a-11e6-978e-7920331c338c.png)

![screenshot 2016-04-15 18 45 03](https://cloud.githubusercontent.com/assets/463790/14568614/3d881924-033a-11e6-9df5-6cb1867be7cb.png)

**Comment by rhuss** [comment] 2016-04-15 19:53
duplicate of #5920

**Closed by rhuss** 2016-04-15 19:53 UTC
