### ISSUE TITLE
fabric8.io DNS is blacklisted

### ISSUE THREAD

**Issue by kastork** [fabric8io/fabric8#5328] opened 2015-11-25 12:28 UTC
I don't know why, but the domain name server for fabric8.io is black listed by the US Navy.  As a result, the fabric8 website cannot be viewed from any Navy network because the domain name won't resolve.  Even if you don't care about the impact to people on Navy networks, you may want to  contact Navy Cyber Defense and figure out the reason they think these name servers are problematic.

This from my network operations folks:
The following domain is on the Navy Cyber Defense Operations Center (NCDOC) blocklist: afraid.org 
the domain: fabric8.io uses ns1.afraid.org, ns2.afraid.org, ns3.afrad.org, and ns4.afraid.org which are all affected by the NCDOC DNS blocklist.

**Comment by gashcrumb** [comment] 2015-11-25 14:01
@kastork, yeah, we should definitely look into this.  Wonder if they don't like *.io domain names in general?

**Comment by jimmidyson** [comment] 2015-11-25 14:02
The problem is the DNS provider (afraid.org) not the domain name.

**Comment by gashcrumb** [comment] 2015-11-25 14:06
Ah, so probably because we're using a free DNS server for our project sites then...  K, who's gonna pony up a credit card to get a proper DNS service?  :-)

**Comment by jimmidyson** [comment] 2015-11-25 14:09
Would you believe we actually do pay? $5 donation :stuck_out_tongue_winking_eye:

**Comment by kastork** [comment] 2015-11-25 16:44
From what I'm told
- there's no general problem with '.io'
- they don't know or care that the service is 'free'.
- the name mismatch is not an issue

Usually, the authority in question black-holes domains when they have some kind of evidence that there's malicious activity going on there.  What qualifies as evidence is a mystery to me -- for  example I don't know if they go out and test servers in some way, or if they only respond to unwelcome activity originating from somewhere. I do know they are extremely conservative, though, and will block a site or service with very little provocation.

Maybe Redhat would donate DNS service?

**Comment by loshkovskyi** [comment] 2015-11-26 11:58
I confirm the nameservers and their web site are also blocked by Cisco CSIRT.

**Comment by jimmidyson** [comment] 2015-11-26 12:01
Looks like cloudflare provide free DNS with wildcard option - let me have a look & see if I can sort that out if that sounds alright @jstrachan?

**Comment by jimmidyson** [comment] 2015-11-26 12:31
We've migrated to Cloudflare DNS so this should be resolved once it has been propagated - could be up to 24 hours, should be very soon.

Closing but would appreciate it if you could reopen if this is still an issue for you. Thanks for reporting!

**Closed by jimmidyson** 2015-11-26 12:31 UTC

**Comment by kastork** [comment] 2015-11-28 15:19
Looks good from our network.  Thanks!

**Comment by jimmidyson** [comment] 2015-11-28 15:21
That's good to hear. Thanks for letting us know.
