### ISSUE TITLE
Can't configure ConfigMap as volumes inside pod using kubernetes-generator in openshift v3

### ISSUE THREAD

**Issue by ravishankarhassain** [fabric8io/fabric8#6138] opened 2016-07-06 10:07 UTC
Hi All, 

I am new to openshift v3. I am trying to modify the generated kubernetes.json using typesafe kubernetes dsl as per http://blog.christianposta.com/typesafe-kubernetes-dsl-for-yaml-json-generation/ to configure ConfigMap as volumes in pod. Then I executed the cmd mvn clean install docker:build fabric8:json fabric8:apply to build and deploy the app in my local openshift which is running inside cdk. I verified the generated kubernetes.json and it has the correct entries.

![image](https://cloud.githubusercontent.com/assets/4846462/16613202/ecea60f8-4362-11e6-97aa-38d912a79585.png)

But when I checked in the openshift console the ReplicationController yaml file doesnt have the proper entires. I have pasted the ReplicationController and the pod yaml files along with the JsonModelProcessor.java in this gist

https://gist.github.com/ravishankarhassain/eccf96585dd8793dd52c0a3eb54619dd

Am I missing anything ?

**Comment by jstrachan** [comment] 2016-07-06 10:15
could you gist the generated json file in `target/classes/kubernetes.json' please?

**Comment by jstrachan** [comment] 2016-07-06 10:17
instead of .withConfigMap(getConfigMapVolumeSource())` can you do `.withNewConfigMap().....endConfigMap()'? That'll make things a little simpler I think

**Comment by ravishankarhassain** [comment] 2016-07-06 10:47
I have updated the gist and also the used .withNewConfigMap().....endConfigMap(). But, still the problem persists.

**Comment by jstrachan** [comment] 2016-07-06 10:53
so it looks like the volume mount is fine:
https://gist.github.com/ravishankarhassain/eccf96585dd8793dd52c0a3eb54619dd#file-kubernetes-json-L71-75
the issue is the volume doesn't define an item to mount:
https://gist.github.com/ravishankarhassain/eccf96585dd8793dd52c0a3eb54619dd#file-kubernetes-json-L81

you can't mount an entire ConfigMap; you can only mount individual items I'm afraid. e.g. like this:
https://github.com/fabric8io/traefik/blob/master/src/main/fabric8/rc.yml#L9-L11

so you will need to update the `withConfigMap` to do a `.withNewItem()....endItem()` to add an item (which maps a key in the ConfigMap to a named file)

**Comment by jstrachan** [comment] 2016-07-06 10:58
actually it does look like you can omit the items: in the 'Use-Case: Consume ConfigMap via volume plugin' section here: http://kubernetes.io/docs/user-guide/configmap/. 

I wonder if manually removing the 'items: []' section of the json you can apply the generated `target/classes/kubernetes.json` file?

Is there an error if you try to apply it?

**Comment by jstrachan** [comment] 2016-07-06 11:05
BTW there's another way to use newlines in a YAML file - for adding stuff to a ConfigMap:
https://github.com/fabric8io/traefik/blob/master/src/main/fabric8/cm.yml#L4

instead of this:
https://gist.github.com/ravishankarhassain/eccf96585dd8793dd52c0a3eb54619dd#file-app-configmap-yaml-L4

which makes the YAML easier to work with

**Comment by ravishankarhassain** [comment] 2016-07-06 15:00
quick update : when I execute mvn clean install and then mvn docker:build fabric8:apply I could see that generated kubernetes.json has been modified correctly and configMap are being mounted as volumes to the pod in the openshift. Thing are working fine as expected.

**Comment by jstrachan** [comment] 2016-07-06 15:03
yay! thanks. Lemme close this for now - we can reopen if something breaks

**Closed by jstrachan** 2016-07-06 15:03 UTC
