### ISSUE TITLE
current vagrant machine seems broken

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5808] opened 2016-03-07 22:08 UTC
just tried twice to do:

```
vagrant destroy -f
vagrant up
```

and both times the router fails to startup
```
$ oc get pods -w
NAME                                 READY     STATUS    RESTARTS   AGE
docker-registry-1-y35fz              1/1       Running   0          25m
fabric8-vwg3h                        1/1       Running   0          35m
fluentd-elasticsearch-172.28.128.4   1/1       Running   0          25m
router-1-deploy                      0/1       Error     0          33m
```

**Comment by jstrachan** [comment] 2016-03-07 22:13
tried scaling down and up the router rc `router-1` to try capture why things fail. Not much luck really.
```
Mar 07 22:12:15 vagrant.f8 openshift[4129]: I0307 22:12:15.535659    4129 event.go:210] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"router-1", UID:"1ec108d7-e4ac-11e5-a369-0800274024d3", APIVersion:"v1", ResourceVersion:"764", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: router-1-xvpqn
Mar 07 22:12:19 vagrant.f8 openshift[4129]: I0307 22:12:19.025349    4129 event.go:210] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"router-1", UID:"1ec108d7-e4ac-11e5-a369-0800274024d3", APIVersion:"v1", ResourceVersion:"779", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: router-1-xvpqn
Mar 07 22:12:20 vagrant.f8 openshift[4129]: W0307 22:12:20.930028    4129 kubelet.go:1915] Orphaned volume "a64ee418-e4b1-11e5-a369-0800274024d3/router-token-hf7an" found, tearing down volume
```

**Comment by oscerd** [comment] 2016-03-07 22:13
It seems to be related to the issue opened by me some days ago #5799

**Comment by jstrachan** [comment] 2016-03-07 22:17
@oscerd thanks! Whats odd is this has been working for many months for me on OS X. No idea why the router has suddenly started acting odd!

**Comment by jstrachan** [comment] 2016-03-07 22:18
I'm wondering if we should try reusing the CDK's vagrantfile - or the OpenShift all in one VM to see if that can at least startup
https://www.openshift.org/vm/

something must have changed with the router in origin

**Comment by oscerd** [comment] 2016-03-07 22:21
Same situation. It has been working on ubuntu for many months and on Centos
too (maybe two months ago was the last time I try a full vagrant up with
success). Weird.
Il 07/mar/2016 23:17, "James Strachan" <notifications@github.com> ha
scritto:

**Comment by jstrachan** [comment] 2016-03-08 05:55
Its looking like OpenShift Origin 1.1.3 changes broke router in the Vagrantfile - no idea why yet. If I switched back to 1.1.2 things work just fine.

I've checked in the 1.1.2 Vagrantfile for now so at least folks can recreate the VM and have a router until we figure out a work around so we can move forward with Origin
https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/openshift-1.1.2

**Comment by davsclaus** [comment] 2016-03-08 06:28
Yeah I had seen the router fail also on osx, and then just destroyed vagrant and started it again, and this 2nd time it worked.

**Comment by jstrachan** [comment] 2016-03-08 06:36
Tried it 3 times and it failed in all 3 :(

**Comment by jstrachan** [comment] 2016-03-08 06:36
I've since tried 1.1.2 of origin 3 times and its worked every time ;)

**Comment by jimmidyson** [comment] 2016-03-08 09:36
Hmm. I've just started a clean Vagrant with 1.1.3 & all works fine for me. I wonder if you can get either the logs of a failed router pod, the router deploy pod & also describes of both those pods?

**Comment by jimmidyson** [comment] 2016-03-08 09:43
Ah it works on libvirt but not on Virtualbox. Can't seem to pull the openshift/origin-deployer:v1.1.3 image?

**Comment by jstrachan** [comment] 2016-03-08 09:45
all the logs I could find are above; there was nothing meaningful in any of the router docker containers that got deleted, the deployer or the journalctl -fu openshift. Maybe this only fails on VirtualBox?

I have seen this work in the past; sometimes it fails, then you trash it and try again and it works again. 

It did seem the router deployer ran, created a pod and then it deletes them, then terminates the pod later on.

**Comment by oscerd** [comment] 2016-03-08 09:46
If you look at #5799 there are the events list and also some logs from different pods.

**Comment by jimmidyson** [comment] 2016-03-08 09:47
No it works for me actually - just had to be more patient. Starts fine with VirtualBox 5.0.16 on Linux, just slow (compared to libvirt).

**Comment by jimmidyson** [comment] 2016-03-08 12:18
I've just merged an upgraded box into fabric8-installer repo - please retry with that & see if it works for you - it works perfectly for me.

**Comment by jstrachan** [comment] 2016-03-08 12:22
it worked first time for me on OS X!

**Comment by jimmidyson** [comment] 2016-03-08 13:00
Then I'm going to close this - we can reopen it if people are still having problems.

**Closed by jimmidyson** 2016-03-08 13:00 UTC
Labels: vagrant

**Comment by oscerd** [comment] 2016-03-08 14:15
I can confirm it works on Centos 7 too

**Comment by jstrachan** [comment] 2016-03-08 14:16
@oscerd yay!!!
