### ISSUE TITLE
cannot run builds in CI/CD project for maven archetype projects

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#5922] opened 2016-04-11 13:35 UTC
paste bin of stack:

http://pastebin.com/Tp2tDAEC

**Comment by rawlingsj** [comment] 2016-04-11 13:37
duplicate of https://github.com/fabric8io/fabric8/issues/5916 release is happening at the moment with the fix

**Closed by rawlingsj** 2016-04-11 13:37 UTC
