### ISSUE TITLE
 Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError

### ISSUE THREAD

**Issue by J0hnson** [fabric8io/fabric8#6608] opened 2016-12-02 07:22 UTC
[root@master1 tmp]# oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.paastest.cn:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

[root@master1 tmp]# docker version
Client:
Version: 1.10.3
API version: 1.22
Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
Go version: go1.6.3
Git commit: cb079f6-unsupported
Built: Fri Sep 16 13:24:25 2016
OS/Arch: linux/amd64

Server:
Version: 1.10.3
API version: 1.22
Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
Go version: go1.6.3
Git commit: cb079f6-unsupported
Built: Fri Sep 16 13:24:25 2016
OS/Arch: linux/amd64

Steps To Reproduce

Download fabric8 0.4.112
Install fabric8 in openshift
gofabric8-linux-amd64 deploy -y --namespace=fabric8 --domain=paastest.cn --app=cd-pipeline
3.All services/pods can work fine except jenkins .
Current Result

The logs:
oc get event

, failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=init pod=jenkins-1-ic1ze_fabric(33c33367-b85c-11e6-be46-00248cfcb938)"
]
13m       13m       1         jenkins-1-ic1ze   Pod       spec.initContainers{init}   Normal    Created      {kubelet node1.paastest.cn}   Created container with docker id 1b3f85e3098a
13m       13m       1         jenkins-1-ic1ze   Pod       spec.initContainers{init}   Normal    Started      {kubelet node1.paastest.cn}   Started container with docker id 1b3f85e3098a
8s        12m       59        jenkins-1-ic1ze   Pod                                   Warning   FailedSync   {kubelet node1.paastest.cn}   Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1"
, failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=init pod=jenkins-1-ic1ze_fabric(33c33367-b85c-11e6-be46-00248cfcb938)"

Can anyone give some advice to troubleshoot?
Appreciate.

**Comment by J0hnson** [comment] 2016-12-05 08:50
I also tried with --pv=false,but the same error information.
Any one can help on this?

**Comment by rawlingsj** [comment] 2017-01-12 09:40
I think this is a duplicate of https://github.com/fabric8io/gofabric8/issues/325 which is resolved now.

**Closed by rawlingsj** 2017-01-12 09:40 UTC
